---
version: 2
sources:
- name: "alias_base_QA_DATABASE_QA_SCHEMA"
  database: "QA_DATABASE"
  schema: "QA_SCHEMA"
  config:
    enabled: true
  tables:
  - name: "ALL_TYPE_TABLE_NON_GEOMETRY"
    columns:
    - name: "C_NUM"
      dataType:
        type: "Number"
    - name: "C_NUM10"
      dataType:
        type: "Number"
    - name: "C_DEC"
      dataType:
        type: "Number"
    - name: "C_NUMERIC"
      dataType:
        type: "Number"
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_INTEGER"
      dataType:
        type: "Number"
    - name: "C_DOUBLE"
      dataType:
        type: "Float"
    - name: "C_FLOAT"
      dataType:
        type: "Float"
    - name: "C_COUBLE_PRECISION"
      dataType:
        type: "Float"
    - name: "C_REAL"
      dataType:
        type: "Float"
    - name: "C_VARCHAR"
      dataType:
        type: "String"
    - name: "C_VARCHAR50"
      dataType:
        type: "String"
    - name: "C_CHAR"
      dataType:
        type: "String"
    - name: "C_CHAR10"
      dataType:
        type: "String"
    - name: "C_STRING"
      dataType:
        type: "String"
    - name: "C_STRING20"
      dataType:
        type: "String"
    - name: "C_TEXT"
      dataType:
        type: "String"
    - name: "C_TEXT30"
      dataType:
        type: "String"
    - name: "C_BINARY"
      dataType:
        type: "Binary"
    - name: "C_BINARY100"
      dataType:
        type: "Binary"
    - name: "C_VARBINARY"
      dataType:
        type: "Binary"
    - name: "C_BOOL"
      dataType:
        type: "Boolean"
    - name: "C_TIMESTAMP"
      dataType:
        type: "Timestamp"
    - name: "C_DATE"
      dataType:
        type: "Date"
    - name: "C_DATETIME"
      dataType:
        type: "Timestamp"
    - name: "C_TIME"
      dataType:
        type: "Time"
    - name: "C_TIMESTAMPLTZ"
      dataType:
        type: "Timestamp"
    - name: "C_TIMESTAMP_NTZ"
      dataType:
        type: "Timestamp"
    - name: "C_VARIANT"
      dataType:
        type: "Variant"
    - name: "C_ARRAY"
      dataType:
        type: "Array"
    - name: "C_OBJECT"
      dataType:
        type: "Object"
    - name: "C_GEOGRAPHY"
      dataType:
        type: "Geography"
- name: "alisa_qa_database_qa_SIMPLE_schema"
  database: "\"qa_database\""
  schema: "\"qa_SIMPLE_schema\""
  config:
    enabled: true
  tables:
  - name: "\"all_type_table\""
    columns:
    - name: "C_NUM"
      dataType:
        type: "Number"
    - name: "C_NUM10"
      dataType:
        type: "Number"
    - name: "C_DEC"
      dataType:
        type: "Number"
    - name: "C_NUMERIC"
      dataType:
        type: "Number"
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_INTEGER"
      dataType:
        type: "Number"
    - name: "C_DOUBLE"
      dataType:
        type: "Float"
    - name: "C_FLOAT"
      dataType:
        type: "Float"
    - name: "C_COUBLE_PRECISION"
      dataType:
        type: "Float"
    - name: "C_REAL"
      dataType:
        type: "Float"
    - name: "C_VARCHAR"
      dataType:
        type: "String"
    - name: "C_VARCHAR50"
      dataType:
        type: "String"
    - name: "C_CHAR"
      dataType:
        type: "String"
    - name: "C_CHAR10"
      dataType:
        type: "String"
    - name: "C_STRING"
      dataType:
        type: "String"
    - name: "C_STRING20"
      dataType:
        type: "String"
    - name: "C_TEXT"
      dataType:
        type: "String"
    - name: "C_TEXT30"
      dataType:
        type: "String"
    - name: "C_BINARY"
      dataType:
        type: "Binary"
    - name: "C_BINARY100"
      dataType:
        type: "Binary"
    - name: "C_VARBINARY"
      dataType:
        type: "Binary"
    - name: "C_BOOL"
      dataType:
        type: "Boolean"
    - name: "C_TIMESTAMP"
      dataType:
        type: "Timestamp"
    - name: "C_DATE"
      dataType:
        type: "Date"
    - name: "C_DATETIME"
      dataType:
        type: "Timestamp"
    - name: "C_TIME"
      dataType:
        type: "Time"
    - name: "C_TIMESTAMPLTZ"
      dataType:
        type: "Timestamp"
    - name: "C_TIMESTAMP_NTZ"
      dataType:
        type: "Timestamp"
    - name: "C_VARIANT"
      dataType:
        type: "Variant"
    - name: "C_ARRAY"
      dataType:
        type: "Array"
    - name: "C_OBJECT"
      dataType:
        type: "Object"
    - name: "C_GEOGRAPHY"
      dataType:
        type: "Geography"
- name: "QA_DATABASE.\"qa_SCHEMA\""
  database: "QA_DATABASE"
  schema: "\"qa_SCHEMA\""
  config:
    enabled: true
  tables:
  - name: "\"all_type_table\""
    columns:
    - name: "C_NUM"
      dataType:
        type: "Number"
    - name: "C_NUM10"
      dataType:
        type: "Number"
    - name: "C_DEC"
      dataType:
        type: "Number"
    - name: "C_NUMERIC"
      dataType:
        type: "Number"
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_INTEGER"
      dataType:
        type: "Number"
    - name: "C_DOUBLE"
      dataType:
        type: "Float"
    - name: "C_FLOAT"
      dataType:
        type: "Float"
    - name: "C_COUBLE_PRECISION"
      dataType:
        type: "Float"
    - name: "C_REAL"
      dataType:
        type: "Float"
    - name: "C_VARCHAR"
      dataType:
        type: "String"
    - name: "C_VARCHAR50"
      dataType:
        type: "String"
    - name: "C_CHAR"
      dataType:
        type: "String"
    - name: "C_CHAR10"
      dataType:
        type: "String"
    - name: "C_STRING"
      dataType:
        type: "String"
    - name: "C_STRING20"
      dataType:
        type: "String"
    - name: "C_TEXT"
      dataType:
        type: "String"
    - name: "C_TEXT30"
      dataType:
        type: "String"
    - name: "C_BINARY"
      dataType:
        type: "Binary"
    - name: "C_BINARY100"
      dataType:
        type: "Binary"
    - name: "C_VARBINARY"
      dataType:
        type: "Binary"
    - name: "C_BOOL"
      dataType:
        type: "Boolean"
    - name: "C_TIMESTAMP"
      dataType:
        type: "Timestamp"
    - name: "C_DATE"
      dataType:
        type: "Date"
    - name: "C_DATETIME"
      dataType:
        type: "Timestamp"
    - name: "C_TIME"
      dataType:
        type: "Time"
    - name: "C_TIMESTAMPLTZ"
      dataType:
        type: "Timestamp"
    - name: "C_TIMESTAMP_NTZ"
      dataType:
        type: "Timestamp"
    - name: "C_VARIANT"
      dataType:
        type: "Variant"
    - name: "C_ARRAY"
      dataType:
        type: "Array"
    - name: "C_OBJECT"
      dataType:
        type: "Object"
    - name: "C_GEOGRAPHY"
      dataType:
        type: "Geography"
  - name: "\"ALL_TYPE_Table\""
    columns:
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_STRING"
      dataType:
        type: "String"
  - name: "\"Employees_qa_SCHEMA\""
    columns:
    - name: "TITLE"
      dataType:
        type: "String"
    - name: "EMPLOYEE_ID"
      dataType:
        type: "Number"
    - name: "MANAGER_ID"
      dataType:
        type: "Number"
- name: "JAFFLE_SHOP.PUBLIC"
  database: "JAFFLE_SHOP"
  schema: "PUBLIC"
  config:
    enabled: true
  tables:
  - name: "\"DeltaO1\""
    columns:
    - name: "A"
      dataType:
        type: "Number"
- name: "\"qa_database\".\"qa_SCHEMA\""
  database: "\"qa_database\""
  schema: "\"qa_SCHEMA\""
  config:
    enabled: true
  tables:
  - name: "\"all_type_table\""
    columns:
    - name: "C_NUM"
      dataType:
        type: "Number"
    - name: "C_NUM10"
      dataType:
        type: "Number"
    - name: "C_DEC"
      dataType:
        type: "Number"
    - name: "C_NUMERIC"
      dataType:
        type: "Number"
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_INTEGER"
      dataType:
        type: "Number"
    - name: "C_DOUBLE"
      dataType:
        type: "Float"
    - name: "C_FLOAT"
      dataType:
        type: "Float"
    - name: "C_COUBLE_PRECISION"
      dataType:
        type: "Float"
    - name: "C_REAL"
      dataType:
        type: "Float"
    - name: "C_VARCHAR"
      dataType:
        type: "String"
    - name: "C_VARCHAR50"
      dataType:
        type: "String"
    - name: "C_CHAR"
      dataType:
        type: "String"
    - name: "C_CHAR10"
      dataType:
        type: "String"
    - name: "C_STRING"
      dataType:
        type: "String"
    - name: "C_STRING20"
      dataType:
        type: "String"
    - name: "C_TEXT"
      dataType:
        type: "String"
    - name: "C_TEXT30"
      dataType:
        type: "String"
    - name: "C_BINARY"
      dataType:
        type: "Binary"
    - name: "C_BINARY100"
      dataType:
        type: "Binary"
    - name: "C_VARBINARY"
      dataType:
        type: "Binary"
    - name: "C_BOOL"
      dataType:
        type: "Boolean"
    - name: "C_TIMESTAMP"
      dataType:
        type: "Timestamp"
    - name: "C_DATE"
      dataType:
        type: "Date"
    - name: "C_DATETIME"
      dataType:
        type: "Timestamp"
    - name: "C_TIME"
      dataType:
        type: "Time"
    - name: "C_TIMESTAMPLTZ"
      dataType:
        type: "Timestamp"
    - name: "C_TIMESTAMP_NTZ"
      dataType:
        type: "Timestamp"
    - name: "C_VARIANT"
      dataType:
        type: "Variant"
    - name: "C_ARRAY"
      dataType:
        type: "Array"
    - name: "C_OBJECT"
      dataType:
        type: "Object"
    - name: "C_GEOGRAPHY"
      dataType:
        type: "Geography"
- name: "\"qa_database_lower_case_only\".\"qa_schema_lower_case\""
  database: "\"qa_database_lower_case_only\""
  schema: "\"qa_schema_lower_case\""
  config:
    enabled: true
  tables:
  - name: "\"employees\""
    columns:
    - name: "TITLE"
      dataType:
        type: "String"
    - name: "EMPLOYEE_ID"
      dataType:
        type: "Number"
    - name: "MANAGER_ID"
      dataType:
        type: "Number"
- name: "alias_base_QA_DATABASE_QA_SIMPLE_SCHEMA"
  database: "QA_DATABASE"
  schema: "QA_SIMPLE_SCHEMA"
  config:
    enabled: true
  tables:
  - name: "ALL_TYPE_TABLE_SMALLER"
    columns:
    - name: "C_NUM"
      dataType:
        type: "Number"
    - name: "C_NUM10"
      dataType:
        type: "Number"
    - name: "C_DEC"
      dataType:
        type: "Number"
    - name: "C_NUMERIC"
      dataType:
        type: "Number"
    - name: "C_INT"
      dataType:
        type: "Number"
    - name: "C_INTEGER"
      dataType:
        type: "Number"
    - name: "C_DOUBLE"
      dataType:
        type: "Float"
    - name: "C_FLOAT"
      dataType:
        type: "Float"
    - name: "C_COUBLE_PRECISION"
      dataType:
        type: "Float"
    - name: "C_REAL"
      dataType:
        type: "Float"
    - name: "C_VARCHAR"
      dataType:
        type: "String"
    - name: "C_VARCHAR50"
      dataType:
        type: "String"
    - name: "C_CHAR"
      dataType:
        type: "String"
    - name: "C_CHAR10"
      dataType:
        type: "String"
    - name: "C_STRING"
      dataType:
        type: "String"
    - name: "C_STRING20"
      dataType:
        type: "String"
    - name: "C_TEXT"
      dataType:
        type: "String"
    - name: "C_TEXT30"
      dataType:
        type: "String"
    - name: "C_BINARY"
      dataType:
        type: "Binary"
    - name: "C_BINARY100"
      dataType:
        type: "Binary"
    - name: "C_VARBINARY"
      dataType:
        type: "Binary"
    - name: "C_BOOL"
      dataType:
        type: "Boolean"
    - name: "C_TIMESTAMP"
      dataType:
        type: "Timestamp"
    - name: "C_DATE"
      dataType:
        type: "Date"
    - name: "C_DATETIME"
      dataType:
        type: "Timestamp"
    - name: "C_TIME"
      dataType:
        type: "Time"
    - name: "C_ARRAY"
      dataType:
        type: "Array"
    - name: "C_OBJECT"
      dataType:
        type: "Object"
    - name: "C_GEOGRAPHY"
      dataType:
        type: "Geography"
  - name: "CUSTOMERS"
    columns:
    - name: "ID"
      dataType:
        type: "Number"
    - name: "FIRST_NAME"
      dataType:
        type: "String"
    - name: "LAST_NAME"
      dataType:
        type: "String"
  - name: "TABLE_COMPLEX_TYPES"
    columns:
    - name: "C_ARRAY_INT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_FLOAT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_STRING"
      dataType:
        type: "Array"
    - name: "C_ARRAY_OBJECT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_ARRAY"
      dataType:
        type: "Array"
    - name: "C_ARRAY_VARIANT"
      dataType:
        type: "Array"
    - name: "C_OBJECT_1"
      dataType:
        type: "Object"
    - name: "C_OBJECT_2"
      dataType:
        type: "Object"
    - name: "C_OBJECT_3"
      dataType:
        type: "Object"
    - name: "C_OBJECT_4"
      dataType:
        type: "Object"
    - name: "C_OBJECT_5"
      dataType:
        type: "Object"
    - name: "C_VARIANT_1"
      dataType:
        type: "Variant"
  - name: "TABLE_COMPLEX_TYPES_1"
    columns:
    - name: "C_ARRAY_INT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_FLOAT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_STRING"
      dataType:
        type: "Array"
    - name: "C_ARRAY_OBJECT"
      dataType:
        type: "Array"
    - name: "C_ARRAY_ARRAY"
      dataType:
        type: "Array"
    - name: "C_ARRAY_VARIANT"
      dataType:
        type: "Array"
    - name: "C_OBJECT_1"
      dataType:
        type: "Object"
    - name: "C_OBJECT_2"
      dataType:
        type: "Object"
    - name: "C_OBJECT_3"
      dataType:
        type: "Object"
    - name: "C_OBJECT_4"
      dataType:
        type: "Object"
    - name: "C_OBJECT_5"
      dataType:
        type: "Object"
    - name: "C_VARIANT_1"
      dataType:
        type: "Variant"
    - name: "C_VARIANT_2"
      dataType:
        type: "Variant"
    - name: "C_VARIANT_3"
      dataType:
        type: "Variant"
    - name: "C_VARIANT_4"
      dataType:
        type: "Variant"
    - name: "C_VARIANT_5"
      dataType:
        type: "Variant"
